version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
      # - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_USER: ${DB_USERNAME}
     POSTGRES_DB: ${DB_DATABASE_NAME}
     PG_DATA: /var/lib/postgresql/data
    networks:
      - webnet
    volumes:
      - api-db:/var/lib/postgresql/data

networks:
  webnet:
volumes:
  api-db:
